parameters:
    env(MESSENGER_TRANSPORT_DSN): "enqueue://default?receiveTimeout=100"

framework:
    messenger:
    reset_on_message: true
    transports:
        default:
            dsn: "%env(MESSENGER_TRANSPORT_DSN)"