# This file contains all default configuration or PaaS

framework:
    session:
        handler_id: "redis://%env(string:default:default_redis_host:REDIS_HOST)%:%env(int:default:default_redis_port:REDIS_PORT)%/%env(int:default:default_redis_database:REDIS_SESSION_DATABASE)%"
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: "redis://%env(string:default:default_redis_host:REDIS_HOST)%:%env(int:default:default_redis_port:REDIS_PORT)%/%env(int:default:default_redis_database:REDIS_CACHE_DATABASE)%"

monolog:
    handlers:
        business_event_handler_buffer:
            level: error

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

storefront:
    theme:
        config_loader_id: Shopware\Storefront\Theme\ConfigLoader\StaticFileConfigLoader
        available_theme_provider: Shopware\Storefront\Theme\ConfigLoader\StaticFileAvailableThemeProvider